MoIS/Models/QrViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoIS.Models
{
    public class QrModel
    {
        public string Content { get; set; }
        public string DeceasedName { get; set; }
        public string NoIC { get; set; }
        public string NoRegistration { get; set; }
    }
}

MoIS/Controllers/QrController.cs
using MoIS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;

namespace MoIS.Controllers
{
    public class QrController : CommonController
    {
        // GET: Qr
        public ActionResult Index()
        {
            return View();
        }

        // GET: Qr
        public ActionResult Qr(string eId)
        {
            int id = Convert.ToInt32(Decrypt(eId));
            DBModels dBModel = new DBModels();
            deceased deceased = dBModel.deceaseds.SingleOrDefault(x => x.DeceasedID == id);
            butiranwari butiranwari = dBModel.butiranwaris.SingleOrDefault(x => x.DeceasedID == id);
            butiranbedahsiasat butiranbedahsiasat = dBModel.butiranbedahsiasats.SingleOrDefault(x => x.DeceasedID == id);

            string c = "UNIT PERUBATAN FORENSIK SARAWAK KAD PENGENALAN MAYAT KES POLIS \n";
            c += "WAD: " + deceased.WadUnit + " \n";
            c += "TEL: " + " \n";
            c += "NAMA: " + deceased.DeceasedName + " \n";
            c += "K/P: " + deceased.NoIC + " \n";
            c += "R/N: " +  " \n";
            c += "UMUR:" + deceased.Age + " \n";
            c += "JANTINA:" + deceased.Gender + " \n";
            c += "KETURUNAN:" + deceased.Race + " \n";
            c += "AGAMMA:" + deceased.Religion + " \n";
            c += "ALAMAT:" + deceased.Address + " \n";
            c += "TARIKH DAN WAKTU DIDAFTAR MASUK:" + deceased.DateOfRegistration + " \n";
            c += "DOKTOR:" + " \n";
            c += "TARIKH DAN WAKTU KEMATIAN:" + deceased.DateOfDeath + " \n";
            c += "JENIS KES POLIS:" + " \n";
            c += "KES B.I.D:" + " \n";
            c += "NAMA WARIS:" + butiranwari.WarisName + " \n";
            c += "ALAMAT:" + butiranwari.Alamat + " \n";
            c += "TEL:" + butiranwari.PhoneNo + " \n";
            c += "POLIS YANG DIHUBUINGI:" + " \n";
            c += "NO:" + " \n";
            c += "BALAI:" + " \n";
            c += "DIHUBUNGI OLEH:" + " \n";
            c += "TARIKH" + " \n";
            c += "WARIS SIMATI TELAH DIHUBUNGI:" + " \n";
            var result = new HomeController().PrintViewToPdf(eId, "DcdPmsDetails");
            var model = new QrModel();
            //ViewData["content"] = content;
            model.Content = c;
            model.DeceasedName = deceased.DeceasedName;
            model.NoIC = deceased.NoIC;
            string noBedahSiasat = "";
            if (butiranbedahsiasat != null && butiranbedahsiasat.NoBedahSiasat != "" && butiranbedahsiasat.NoBedahSiasat != null)
            {
                noBedahSiasat = " (" + butiranbedahsiasat.NoBedahSiasat + ")";
            }
            model.NoRegistration = "FORHUS " + deceased.DeceasedID + "/" + deceased.DateOfRegistration.Year + noBedahSiasat;

            return View(model);
        }

        // GET: Qr/QrDetails/5
        public ActionResult QrDetails(string eId, string type = "normal")
        {
            int id = Convert.ToInt32(Decrypt(eId));
            DBModels dBModel = new DBModels();
            deceased deceasedData = dBModel.deceaseds.SingleOrDefault(x => x.DeceasedID == id);
            butiranbedahsiasat butiranbedahsiasatData = dBModel.butiranbedahsiasats.SingleOrDefault(x => x.DeceasedID == id);

            string noBedahSiasat = "";
            if (butiranbedahsiasatData != null)
            {
                if (butiranbedahsiasatData.NoBedahSiasat != "" && butiranbedahsiasatData.NoBedahSiasat != null)
                {
                    noBedahSiasat = " (" + butiranbedahsiasatData.NoBedahSiasat + ")";
                }
            }

            var deceased = dBModel.deceaseds.Where(x => x.DeceasedID == id).ToList();
            var butiranwari = dBModel.butiranwaris.Where(x => x.DeceasedID == id).ToList();

            var model = new DetailsViewModel()
            {
                deceasedList = deceased,
                butiranwariList = butiranwari,
                NoRegistration = "FORHUS " + deceasedData.DeceasedID + "/" + deceasedData.DateOfRegistration.Year + noBedahSiasat
            };
            string DomainUrl = "http://localhost:65100";
            ViewData["DomainUrl"] = DomainUrl;
            ViewData["eId"] = eId;
            if (type == "print")
            {
                ViewData["print"] = "print";
            }
            return View(model);
        }

        public ActionResult PrintViewToPdf(string eId, string page)
        {
            var report = new ActionAsPdf(page, new { eId = eId, type = "print" });
            return report;
        }
    }
}

MoIS/Views/Qr/Qr.cshtml
@model MoIS.Models.QrModel
@using MoIS.Helper

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @Html.GenerateQrCode(@Model.Content)
        <p>Nama Simati: @Model.DeceasedName</p>
        <p>No. Kad Pengenalan: @Model.NoIC</p>
        <p>No. Pendaftaran: @Model.NoRegistration</p>

        <button id="closeBtn" class="btn btn-default">Close</button>
        <button id="printBtn" class="btn btn-default">Print</button>
    </div>
</body>
</html>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $('#closeBtn').click(function () {
        window.top.close();
    });
    $('#printBtn').click(function () {
        window.print();
    });
</script>

MoIS/Views/Qr/QrDetails.cshtml
@model MoIS.Models.DetailsViewModel
@using MoIS.Helper

@{
    if (Session["maID"] == null && @ViewData["print"] != "print")
    {
        Response.Redirect("~/Login/Index");
    }
    var symbol = "@";
}
@if (@ViewData["print"] == "print")
{
    <style>
        #details, #buttons, .navbar-fixed-top {
            display: none !important;
        }
        #printView {
            text-align: center !important;
        }
    </style>
}
<div class="container" style="width:100%;margin-top:2%">
    <ul class="list-group">
        @foreach (var item in Model.deceasedList)
        {
            foreach (var item2 in Model.butiranwariList)
            {
                <pre style="text-align:center;">UNIT PERUBATAN FORENSIK SARAWAK
KAD PENGENALAN MAYAT
KES POLIS</pre>
                <li class="list-group-item" id="details">
                    <table width="100%" style="border:none;">
                        <tbody>
                            <tr>
                                <td style="padding-left: 5px;" colspan="3">WAD: @item.WadUnit</td>
                                <td style="padding-left: 5px;">TEL: </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;">NAMA: @item.DeceasedName</td>
                                <td style="padding-left: 5px;">K/P: @item.DeceasedID</td>
                                <td style="padding-left: 5px;" colspan="2">R/N: </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;">UMUR: @item.Age</td>
                                <td style="padding-left: 5px;">JANTINA: @item.Gender</td>
                                <td style="padding-left: 5px;">KETURUNAN: @item.Race</td>
                                <td style="padding-left: 5px;">AGAMA: @item.Religion</td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="3">TARIKH DAN WAKTU DIDAFTAR MASUK: @string.Format("{0:yyyy-mm-dd}", @item.DateOfRegistration) @symbol @string.Format("{0:H:mm:ss}", @item.DateOfRegistration)</td>
                                <td style="padding-left: 5px;">DOKTOR: </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="4">TARIKH DAN WAKTU KEMATIAN: @string.Format("{0:yyyy-mm-dd}", @item.DateOfDeath) @symbol @string.Format("{0:H:mm:ss}", @item.DateOfDeath)</td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="3">JENIS KES POLIS: </td>
                                <td style="padding-left: 5px;">KES B.I.D: YA/TIDAK</td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="2">NAMA WARIS: @item2.WarisName</td>
                                <td style="padding-left: 5px;">ALAMAT: @item2.Alamat</td>
                                <td style="padding-left: 5px;">NAMA WARIS: @item2.PhoneNo</td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="2">POLIS YANG DIHUBUNGI: </td>
                                <td style="padding-left: 5px;">NO: </td>
                                <td style="padding-left: 5px;">BALAI: </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="2">DIHUBUNGI OLEH S/R, S/N, MA: </td>
                                <td style="padding-left: 5px;" colspan="2">TARIKH: </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 5px;" colspan="2">WARISAN TELAH DIHUBUNGI: YA/TIDAK</td>
                                <td style="padding-left: 5px;" colspan="2">
                                    <label class="control-label col-md-4">BIOHAZARD</label>
                                    <div class="col-md-8">
                                        <input class="form-control" type="checkbox" />
                                    </div>
                                    <label class="control-label col-md-4">YA/TIDAK</label>
                                    <div class="col-md-8">
                                        <input class="form-control" type="checkbox" />
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </li>
                <div class="row" id="printView">
                    <div class="" style="display:inline-block;" id="QRImg">@Html.GenerateQrCode(@ViewData["DomainUrl"] + "/Qr/QrDetails?eId=" + @ViewData["eId"])</div>
                    <div class="" style="display:inline-block;">
                        <p>Nama Simati: @item.DeceasedName</p>
                        <p>No. Kad Pengenalan: @item.NoIC</p>
                        <p>No. Pendaftaran: @Model.NoRegistration</p>
                        <div id="buttons">
                            <button id="closeBtn" class="btn btn-default">Close</button>
                            @Html.ActionLink("Print Qr Code", "PrintViewToPdf", "Qr", new { eId = @ViewData["eId"], page = "QrDetails" }, htmlAttributes: new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>


            }
        }
    </ul>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $('#closeBtn').click(function () {
        window.top.close();
    });
    $('#printBtn').click(function () {
        window.print();
    });
</script>